server:
  port: 8081
spring:
  profiles:
    active:
    - dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dz_Item?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456    